### ISSUE TITLE
Unhandled Exception: Unsupported operation: Isolate.resolvePackageUri

### ISSUE THREAD

**Issue by jveryspace** [rmawatson/flutter_isolate#102]
Flutter 2.10.0
error only on IOS, multiple flutter engine
code:
let newEngine = appDelegate.engines.makeEngine(withEntrypoint: entryPoint, libraryURI: "package:fsapp/env/test.dart")
super.init(engine: newEngine, nibName: nil, bundle: nil)
error:
//
2022-02-09 20:28:14.298442+0800 Runner[1197:362070] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Unsupported operation: Isolate.resolvePackageUri
#0      Isolate.resolvePackageUri (dart:isolate-patch/isolate_patch.dart:335:7)
#1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:369:30)
#2      compute (package:flutter/src/foundation/_isolates_io.dart:22:17)

**Comment by nmfisher** [comment]
Can you provide a sample project to reproduce this issue? Without any further information it looks like a Flutter/Dart isolate issue.
