### ISSUE TITLE
cannot use compute in the iOS FlutterIsolate

### ISSUE THREAD

**Issue by vishna** [rmawatson/flutter_isolate#5]
It might be something I'm doing wrong but on Android the following code piece...

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:isolate';
import 'package:flutter_isolate/flutter_isolate.dart';


void main() {
  runApp(MyApp());
  _createIsolate().then((_) {
    print("sending message to isolate");
    _sendPort.send("message from main");
  });
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Text(""),
    );
  }
}

SendPort _sendPort;
FlutterIsolate _isolate;

Future<void> _createIsolate() async {

  ReceivePort receivePort = ReceivePort();

  _isolate = await FlutterIsolate.spawn(
    _isolateEntry,
    receivePort.sendPort,
  );

  _sendPort = await receivePort.first;
}


void _isolateEntry(SendPort callerSendPort) {

  ReceivePort newIsolateReceivePort = ReceivePort();

  callerSendPort.send(newIsolateReceivePort.sendPort);

  newIsolateReceivePort.listen((dynamic message) {
    print("isolate got message: $message");
    _isolateOperation();
  });
}

void _isolateOperation() async {
  print("performing operation in an isolate");
  try {
    String foo = "echo";
    print("foo = $foo");
    String bar = await compute(_process, foo); // this line breaks for iOS
    print("bar = $bar");
  } catch (error, stacktrace) {
    print(error);
    print(stacktrace);
  }
}

String _process(String input) {
  final output = "$input $input";
  return output;
}
```

...will just work and get you this output:

```
sending message to isolate
isolate got message: message from main
performing operation in an isolate
foo = echo
bar = echo echo
```

...whereas iOS Simulator will give you the following

```
sending message to isolate
isolate got message: message from main
performing operation in an isolate
foo = echo
Unsupported operation: Isolate.resolvePackageUri
#0      Isolate.resolvePackageUri (dart:isolate/runtime/libisolate_patch.dart:340:7)
#1      Isolate.spawn (dart:isolate/runtime/libisolate_patch.dart:377:32)
<asynchronous suspension>
#2      compute (package:flutter/src/foundation/isolates.dart:54:41)
<asynchronous suspension>
#3      _isolateOperation (package:sqlisolate/main.dart:62:24)
<asynchronous suspension>
#4      _isolateEntry.<anonymous closure> (package:sqlisolate/main.dart:53:5)
#5      _rootRunUnary (dart:async/zone.dart:1136:13)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#11     _StreamController._add (dart:async/stream_controller.dart:640:7)
#12     _StreamController.add (dart:async/stream_controll<…>
```

Is this an expected outcome?

**Comment by rmawatson** [comment]
[This ]( https://github.com/flutter/flutter/issues/14815) is possibly related?

**Comment by vishna** [comment]
It could be though it also looks like something iOS related - e.g. using sqflite from flutter_isolate also fails (silently) while working just fine on Android.

**Comment by vishna** [comment]
the sqflite issue I was getting was [fixed here](https://github.com/tekartik/sqflite/commit/652979194de6e10352cfa096772865671799a817) so I guess it's just that `Isolate.resolvePackageUri` thing now

**Comment by jasonkaruza** [comment]
I too am having an issue with getting it to work on iOS in release mode. The following error occurs when trying to download an image from a URL:

```[        ] ../../third_party/dart/runtime/vm/native_entry.cc: 222: error: Failed to resolve native function 'Window_sendPlatformMessage' in
'Window._sendPlatformMessage@132065589'```

The code is using the Flutter Cache Manager plugin https://pub.dartlang.org/packages/flutter_cache_manager:
```dart
FlutterIsolate isolate = await FlutterIsolate.spawn(downloadFiles, urls);

Future<void> downloadFiles(List<String> urls) async {
  for (String url in urls) {
    try {
      print("Retrieving $url...");
      await CacheManager().getSingleFile(url);
    } catch (error, stack) {
      print("Failed to download file $url: $error, $stack");
    }
  }
}
```

**Comment by rmawatson** [comment]
that can't be the whole error. without trying it, I have no idea. Have you tried narrowing it by stepping through the code and seeing where this actually occurs ?

**Comment by nmfisher** [comment]
Given the length of time that's elapsed since this issue was opened, I'll close unless a response is received in the next 7 days.
