### ISSUE TITLE
HotRestart Crashed

### ISSUE THREAD

**Issue by sunjianan9900** [rmawatson/flutter_isolate#59]
Flutter (Channel dev, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64,
    locale zh-Hans-CN)

PLANTFORM IOS
hot reload is fun , crashed on hot restart

```
 [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: 'dart:ui/isolate_name_server.dart': Failed assertion: line 36: '<optimized out>': 'name' cannot be null.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      IsolateNameServer.lookupPortByName (dart:ui/isolate_name_server.dart:36:12)
#3      FlutterIsolate._isolateInitialize.<anonymous closure> (package:flutter_isolate/flutter_isolate.dart:108:42)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#8      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#11     _ro<…>
Lost connection to device.
 
```

**Comment by nmfisher** [comment]
Thanks - I've just taken over as maintainer so I will close this in favour of 
https://github.com/rmawatson/flutter_isolate/issues/72 which is tracking hot restart issues.
