### ISSUE TITLE
PlatformException / flutter_isolate 2.0.0

### ISSUE THREAD

**Issue by moodstubos** [rmawatson/flutter_isolate#74]
Hi, 
I got this Exception notification after using catcher in one of my apps:

```
PlatformException(error, java.lang.Integer cannot be cast to java.lang.Long, null, java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at com.rmawatson.flutterisolate.FlutterIsolatePlugin.onMethodCall()
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage()
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart()
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage()
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

using 
`[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale de-DE)`

**Comment by nmfisher** [comment]
Can you please paste the Dart code where you create the isolate, including the entrypoint function.

**Comment by nmfisher** [comment]
Let me know if you're still experiencing this issue, otherwise I will close.
