### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by jaydip-pawar** [rmawatson/flutter_isolate#80]
This is my sample code:

```
@override
  void initState() {
    isolateMethod();
    super.initState();
  }

void isolateMethod() async {
    final isolate = await FlutterIsolate.spawn(isolated, "");
  }

  void isolated(String args) {
    print("ISOLATED");
  }
```

After running this code I got following exception:

```
E/flutter (  803): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (  803): #0      FlutterIsolate.spawn (package:flutter_isolate/flutter_isolate.dart:26:54)
E/flutter (  803): #1      _AddingDeviceScreenState.isolateMethod (package:smartify/screens/adding_device_screen.dart:73:42)
E/flutter (  803): #2      _AddingDeviceScreenState.initState (package:smartify/screens/adding_device_screen.dart:29:5)
E/flutter (  803): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4711:57)
E/flutter (  803): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
E/flutter (  803): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (  803): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (  803): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6083:14)
E/flutter (  803): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (  803): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (  803): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
E/flutter (  803): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
E/flutter (  803): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
E/flutter (  803): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
E/flutter (  803): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (  803): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (  803): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6083:14)
E/flutter (  803): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (  803): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (  803): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6083:14)
E/flutter (  803): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (  803): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (  803): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
E/flutter (  803): #23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
E/flutter (  803): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
E/flutter (  803): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
E/flutter (  803): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4737:11)
E/flutter (  803): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
E/flutter (  803): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (  803): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (  803): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6083:14)
E/flutter (  803): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (  803): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (  803): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6083:14)
E/flutter (  803): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (  803): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (  803): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
E/flutter (  803): #37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
E/flutter (  803): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
E/flutter (  803): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
E/flutter (  803): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4737:11)
E/flutter (  803): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
E/flutter (  803): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (  803): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (  803): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
E/flutter (  803): #45     Element.rebuild (package:flutter/src/widgets/f
```

**Comment by nmfisher** [comment]
Your entry point function (isolated) needs to be a top level or static function.
